package org.ucb.c5.composition.checkers;

import org.ucb.c5.sequtils.RevComp;

/**
 * Checks to see if RnasESites Test works as intended. By Naveen Kumaran
 */
public class RNAseE_Site_Checker {

    private RevComp revcomp;

    public void initiate() throws Exception {
        revcomp = new RevComp();
        revcomp.initiate();
    }

    public boolean run(String sequence) throws Exception {
        boolean out = true;
        String upper = sequence.toUpperCase();
        String revseq = revcomp.run(upper);

        boolean result1 = checkRNAseE(upper);
        boolean result2 = checkRNAseE(revseq);

        if (result1 == false) {
            return false;
        }
        if (result2 == false) {
            return false;
        }
        return true;
    }

    private boolean checkRNAseE(String sequence) {
        int window_size = 10;
        for (int i = 0; i < sequence.length() - window_size; i++) {
            String window = sequence.substring(i, i + window_size);

            //Does the window have at least 4 T's in a row?
            boolean violatesT = window.contains("TTTT");

            //How many T's are in the window?
            int counter = 0;
            for (int k = 0; k < window_size; k++) {
                char base = window.charAt(k);
                if (base == 'A' || base == 'T') {
                    counter++;
                }
            }

            //If there are at least 8 A's or T's, the second criterisa is true
            boolean violates80 = counter >= 8;

            //If both criteria are met, a site is present, return false
            if (violates80 && violatesT) {
                return false;
            }
        }

        return true;
    }

    public static void main(String[] args) throws Exception {
        RNAseE_Site_Checker checker = new RNAseE_Site_Checker();
        checker.initiate();

        //A seq that definitvely lacks sites
        boolean result = checker.run("CGGCGGCG");
        System.out.println("CGGCGGCGGCGC (true): " + result);

        //A Promoter seq that contains sites
        result = checker.run("ttatgacaacttgacggctacatcattcactttttcttcacaaccggcacggaactcgctcgggctggccccggtgcattttttaaatacccgcgagaaatagagttgatcgtcaaaaccaacattgcgaccgacggtggcgataggcatccgggtggtgctcaaaagcagcttcgcctggctgatacgttggtcctcgcgccagcttaagacgctaatccctaactgctggcggaaaagatgtgacagacgcgacggcgacaagcaaacatgctgtgcgacgctggcgatatcaaaattgctgtctgccaggtgatcgctgatgtactgacaagcctcgcgtacccgattatccatcggtggatggagcgactcgttaatcgcttccatgcgccgcagtaacaattgctcaagcagatttatcgccagcagctccgaatagcgcccttccccttgcccggcgttaatgatttgcccaaacaggtcgctgaaatgcggctggtgcgcttcatccgggcgaaagaaccccgtattggcaaatattgacggccagttaagccattcatgccagtaggcgcgcggacgaaagtaaacccactggtgataccattcgcgagcctccggatgacgaccgtagtgatgaatctctcctggcgggaacagcaaaatatcacccggtcggcaaacaaattctcgtccctgatttttcaccaccccctgaccgcgaatggtgagattgagaatataacctttcattcccagcggtcggtcgataaaaaaatcgagataaccgttggcctcaatcggcgttaaacccgccaccagatgggcattaaacgagtatcccggcagcaggggatcattttgcgcttcagccatacttttcatactcccgccattcagagaagaaaccaattgtccatattgcatcagacattgccgtcactgcgtcttttactggctcttctcgctaaccaaaccggtaaccccgcttattaaaagcattctgtaacaaagcgggaccaaagccatgacaaaaacgcgtaacaaaagtgtctataatcacggcagaaaagtccacattgattatttgcacggcgtcacactttgctatgccatagcatttttatccataagattagcggatcctacctgacgctttttatcgcaactctctactgtttctccatacccgtttttttgggctagcacgaatccgactctcacattatcaggggtataaaaATGGCGCTGTTGTCAAGTTCACTTAGCAGCCAAATCCCAACCGGTTCCCACCCCCTCACGCACACACAGTGTATACCGCATTTCTCGACCACTATAAACGCCGGTATCAGCGCCGGTAAGCCTCGATCTTTTTACTTGAGGTGGGGCAAAGGTTCCAACAAGATTATTGCATGTGTCGGGGAGGGGACTACTTCTCTGCCTTATCAAAGCGCTGAGAAGACCGATAGTTTGTCAGCTCCCACACTCGTGAAAAGGGAGTTTCCGCCAGGGTTCTGGAAAGATCATGTTATCGATTCACTGACGAGTAGCCACAAGGTCAGCGCGGCAGAGGAAAAACGGATGGAAACATTAATAAGCGAAATCAAGAATATCTTTCGGTCAATGGGCTATGGGGAAACCAATCCGTCGGCGTACGATACAGCTTGGGTCGCTCGCATACCAGCTGTCGATGGATCAGAACACCCCGAGTTCCCAGAGACATTAGAGTGGATTCTCCAAAATCAGCTCAAAGATGGTAGCTGGGGGGAAGGCTTCTACTTCCTTGCCTACGACAGGATTCTGGCAACGTTGGCGTGCATAATAACGTTAACTCTTTGGCGGACCGGAGAAACCCAAATAAGGAAAGGCATTGAGTTCTTTAAAACTCAGGCCGGAAAGATTGAAGATGAAGCCGATTCTCACAGGCCGTCTGGGTTCGAGATCGTCTTCCCGGCGATGTTAAAAGAGGCTAAAGTTCTGGGGTTTTTTTTACCCTACGAATTGCCATTTATAAAGCAGATCATCGAAAAACGGGAGGCTAAGTTGGAACGATTACCTACTAATATATTGTACGCCCTGCCAACGACGCTACTCTACTCACTTGAGGGATTGCAGGAGATCGTTGATTGGGAAAAGATAATTAAACTACAATCCAAGGACGGAAGTTTCTTAACGAGCCCCGCTTCGACGGCCGCGGTTTTCATGCGGACTGGGAATAAGAAGTGCCTTGAGTTCCTTAACTTCGTCCTTAAGAAATTCGGAAACCACGTTCCATGTCACTACCCCCTTGACTTGTTCGAACGTTTATGGGCGGTAGACACGGTTGAGCGGTTGGGCATCGACCACCATTTTAAGGAGGAAATTAAGGATGCACTCGATTACGTATATTCGCACTGGGATGAACGCGGGATTGGGTGGGCCAGAGAGAACCCTATTCCAGATATTGACGACACCGCAATGGGCTTAAGAATATTACGGCTGCACGGCTATAACGTGAGCTCAGACGTGTTGAAGACTTTTCGTGACGAGAATGGGGAGTTTTTCTGCTTCCTCGGGCAAACACAAAGAGGCGTCACAGATATGTTAAACGTTAACCGCTGTTCGCATGTGGCGTTCCCGGGTGAAACAATCATGCAGGAAGCTAAATTATGCACGGAGCGATATCTTCGAAACGCACTAGAGGATGTAGGTGCGTTCGACAAATGGGCTCTGAAAAAGAACATCCGGGGCGAAGTAGAGTATGCATTAAAGTACCCGTGGCACCGCTCCATGCCTAGGTTAGAAGCTCGTAGTTATATAGAGCACTATGGGCCTAACGACGTGTGGCTGGGGAAAACTATGTACATGATGCCTTATATTAGTAACCTGAAATATCTTGAGTTGGCTAAGCTGGATTTCAATCATGTCCAGTCGCTACACCAAAAGGAGCTTAGAGACTTACGTCGATGGTGGAAATCGTCGGGTCTGTCAGAGCTGAAGTTTACAAGAGAACGCGTGACTGAGATTTACTTCTCGGCGGCCTCTTTCATATTTGAACCGGAATTTGCTACTTGTAGGGATGTCTACACAAAAATCAGTATATTTACGGTGATTCTGGACGATCTCTATGATGCCCATGGGACTCTGGACAACCTTGAGCTTTTCAGTGAGGGTGTCAAACGGTGGGATTTATCGTTAGTAGATCGTATGCCGCAGGATATGAAAATTTGCTTCACAGTTCTGTACAATACGGTTAACGAGATCGCTGTGGAAGGCAGAAAACGCCAAGGGCGCGATGTACTCGGATACATTAGAAACGTCCTCGAAATCTTACTCGCGGCACATACCAAGGAGGCAGAATGGTCGGCCGCTCGTTACGTTCCTTCCTTTGATGAATATATTGAGAACGCGTCCGTTTCGATCTCTCTCGGAACGTTGGTTCTCATATCTGTTCTCTTCACTGGGGAAATTCTCACCGATGATGTATTATCTAAGATTGGCCGTGGATCGAGGTTTCTACAGCTTATGGGACTGACAGGGCGCCTCGTTAATGACACTAAGACCTATGAAGCAGAAAGAGGTCAGGGCGAGGTAGCGTCGGCAGTCCAATGCTATATGAAGGAACATCCCGAGATATCCGAGGAGGAAGCGTTAAAACATGTGTATACAGTTATGGAAAATGCCCTAGACGAGTTGAACAGAGAATTTGTCAACAACCGTGATGTCCCTGACTCGTGCAGGCGCTTGGTTTTTGAAACAGCTAGGATAATGCAGTTATTTTATATGGAGGGGGACGGGCTGACGTTAAGTCACGAAATGGAAATAAAAGAGCACGTAAAGAATTGTCTATTTCAGCCGGTGGCTgttgaccgagcactgtgattttttgaggtaacaagATGTATCCCTTCATACGCACGGCCAGAATGACGGTCTGCGCGAAGAAACACGTGCACCTTACAAGGGACGCGGCAGAGCAACTGCTCGCCGATATCGACAGACGCCTGGATCAACTCTTACCAGTGGAGGGTGAACGTGACGTTGTCGGGGCAGCCATGCGGGAAGGGGCTCTAGCTCCGGGCAAAAGAATAAGGCCCATGCTATTACTTCTCACTGCGCGTGATCTGGGGTGTGCAGTCTCTCATGATGGCCTATTGGACCTTGCCTGCGCGGTTGAGATGGTTCACGCCGCGAGTTTAATCCTTGATGACATGCCCTGTATGGATGACGCTAAACTCAGGCGCGGGCGGCCTACCATTCATAGCCACTATGGTGAGCACGTGGCGATCTTAGCTGCCGTCGCACTACTTTCGAAGGCGTTCGGTGTCATAGCTGATGCGGACGGACTTACGCCATTAGCTAAGAACCGGGCAGTATCGGAATTGAGTAATGCGATCGGTATGCAGGGGCTTGTCCAAGGCCAGTTCAAGGACCTGAGCGAGGGAGACAAACCTAGATCCGCTGAAGCGATCCTCATGACCAACCATTTCAAAACATCGACGCTCTTCTGTGCCTCTATGCAGATGGCTTCAATAGTGGCAAATGCGTCTTCTGAAGCGCGCGACTGCTTGCACCGATTCTCCTTGGACTTGGGTCAGGCCTTCCAACTTTTAGATGACCTCACAGACGGTATGACCGACACTGGGAAGGACAGTAACCAGGATGCAGGGAAATCAACACTTGTGAACCTATTAGGTCCCAGGGCGGTTGAAGAACGGCTTCGGCAACACCTCCAGCTCGCCTCTGAACACCTCTCCGCGGCTTGCCAACATGGCCATGCTACCCAACATTTTATCCAAGCCTGGTTCGACAAGAAACTTGCCGCAGTTAGCTGCCTGGCGGCAGTAGCGCGGTGGTCCCACCTGACCCCATGCCGAACTCAGAAGTGAAACGCCGTAGCGCCGATGGTAGTGTGGGGTCTCCCCATGCGAGAGTAGGGAACTGCCAGGCATCAAATAAAACGAAAGGCTCAGTCGAAAGACTGGGCCTT");
        System.out.println("promoter example (false): " + result);

        //A seq that for sure has the pattern
        result = checker.run("TTTTTTTTTTTTT");
        System.out.println("poly-T (false): " + result);
    }
}
